### ISSUE TITLE
Uploading photos doesn't work

### ISSUE THREAD

**Issue by dcollinsn** [insrcd/PreRegMePublic#10]
I have uploaded an actual picture this time. (It is a .jpg) I wait for the photo to populate, and click "save". The "Profile saved" message comes up. I see the following:

![image](https://cloud.githubusercontent.com/assets/9273956/12436271/bc03e0dc-bee1-11e5-975c-d507921a1bde.png)

I see that the image was stored at https://prereg.me/binary/image/8a7e8082525c54b001525c68d48f0008

I load the profile page again, and the image is gone:

![image](https://cloud.githubusercontent.com/assets/9273956/12436314/10442fd0-bee2-11e5-8bc1-f2b81a1a86f9.png)

**Comment by insrcd** [comment]
This should be resolved.
