### ISSUE TITLE
Profile - "Bio" box doesn't load saved bio properly

### ISSUE THREAD

**Issue by dcollinsn** [insrcd/PreRegMePublic#11]
When I reload the profile page, the "Bio" is empty, even though the HTML textarea element has data in it from a previous saved bio.

![image](https://cloud.githubusercontent.com/assets/9273956/12436541/4061b820-bee4-11e5-8763-015a5ed5a9c8.png)

Google Chrome, Windows 7.

**Comment by insrcd** [comment]
Fixed
