### ISSUE TITLE
Can't search for friends: HTTP 403

### ISSUE THREAD

**Issue by dcollinsn** [insrcd/PreRegMePublic#12]
From the profile page, opening the "friends" dropdown and typing one or more characters results in JSON requests to https://prereg.me/user/search.json, which results in HTTP 403 errors. The content is:

`{
  "error": "access denied"
}`

![image](https://cloud.githubusercontent.com/assets/9273956/12436603/bfb435ee-bee4-11e5-9bdd-cdfbc48eca85.png)

**Comment by insrcd** [comment]
I have opened up ROLE_USER to search the user list.

**Comment by dcollinsn** [comment]
This still returns `{"error": "access denied"}` and HTTP 403 to the JSON request to `https://prereg.me/user/search.json`

**Comment by insrcd** [comment]
Indeed, I need to add the MANAGER role.

Adam
