### ISSUE TITLE
Adding a membership appears to fail when it actually succeeded

### ISSUE THREAD

**Issue by dcollinsn** [insrcd/PreRegMePublic#13]
When adding a new membership on the profile page by:

* Selecting "Magic"
* Typing in a DCI number
* Pressing the Enter key (without first removing focus from the DCI number entry box)

The new membership appears momentarily, but then (because I pressed Enter) the page makes a GET request to `https://prereg.me/profile?brand=Magic&identifier=8102291717`, which looks like:

![image](https://cloud.githubusercontent.com/assets/9273956/12436764/17ad2818-bee6-11e5-99e9-ffbead8c90e9.png)

And the new membership is not visible. Reloading the profile fixes this.

**Comment by insrcd** [comment]
The form was being submitted on enter which was preventing the AJAX from working - I've resolved this for the next push (thanks for the super clear bug report).
