### ISSUE TITLE
Privacy/Communications Settings never unfade

### ISSUE THREAD

**Issue by dcollinsn** [insrcd/PreRegMePublic#14]
When first loading the profile:

![image](https://cloud.githubusercontent.com/assets/9273956/12436839/95733f4e-bee6-11e5-8cd1-5fbfd7e4851c.png)

After focusing and then unfocusing the Privacy form-group:

![image](https://cloud.githubusercontent.com/assets/9273956/12436864/c9d93676-bee6-11e5-8e0d-3474a0738f78.png)

The `form-group` `div` does successfully get `focused` applied and then removed, but the `labels` never get `fade` removed.

**Comment by insrcd** [comment]
They shouldn't fade at all anymore.
