### ISSUE TITLE
Unable to register for events

### ISSUE THREAD

**Issue by dcollinsn** [insrcd/PreRegMePublic#15]
I have changed the "registration end" date for the Beta event, and attempted to register for it:

`There was an error in creating your registration You have passed a blank string for 'card'. You should remove the 'card' parameter from your request or supply a non-blank value.`

![image](https://cloud.githubusercontent.com/assets/9273956/12462414/2cf823a2-bf8c-11e5-91cb-9729e329b03d.png)

**Comment by dcollinsn** [comment]
The current error looks like:

`There was an error in creating your registration You did not provide an API key, though you did set your Authorization header to "Bearer". Using Bearer auth, your Authorization header should look something like 'Authorization: Bearer YOUR_SECRET_KEY'. See https://stripe.com/docs/api#authentication for details, or we can help at https://support.stripe.com/.Register`

**Comment by insrcd** [comment]
NOTE: Don't allow event creation / signup unless the channel is created
properly.

**Comment by dcollinsn** [comment]
currently fixed by RTFM. Will open a new ticket for any payment issues
