### ISSUE TITLE
Unable to save changes for event registration type

### ISSUE THREAD

**Issue by dcollinsn** [insrcd/PreRegMePublic#17]
When attempting to edit an event registration type - for example, editing the description of the "Basic Registration" to the "Beta" event - it is impossible to save changes. I have clicked on the existing text to open the text box, replaced the ending period with an exclamation mark, and clicked "save". The "Event saved" popup appears at the lower right. However, upon reloading the page, changes were not saved.

However, when modifying that text box and then pressing the "Enter" key, a strange thing occurs. A new, mostly blank line appears below, with no name, price or delete option:

![image](https://cloud.githubusercontent.com/assets/9273956/12462613/3c9032ea-bf8d-11e5-9e6e-7ea01c0ab4cb.png)

Upon reloading, we see that is *does* save the modifications to the existing row, but *does not* save the new "phantom" row:

![image](https://cloud.githubusercontent.com/assets/9273956/12462632/5828497a-bf8d-11e5-8b9a-ccaaa4c9ba8c.png)

**Comment by dcollinsn** [comment]
I've discovered that this is because hitting enter in the text box for "This is the basic registration for all users?" actually submits the form *above*, attempting to "add" a new row. That new row is not saved.

**Comment by insrcd** [comment]
I'm going to redesign this form to make it a little easier to deal with.

**Comment by dcollinsn** [comment]
Improved in dev.
