### ISSUE TITLE
Registration form asks for membership number, but not a game system

### ISSUE THREAD

**Issue by dcollinsn** [insrcd/PreRegMePublic#18]
The registration form, `http://preregdev.cfapps.io/site/register`, asks for a membership number. Currently, the only game system is Magic. However, all other places where you can enter a membership number do ask for a game system. The registration form should allow the user to select what system they are entering a membership number form

**Comment by insrcd** [comment]
It defaults to magic right now as that is the only type of event we're currently marketing too, but I'm aware that this is going to have to change.  I have to futz around with the workflow a bit - I'll most likely be removing it from the registration and instead having event creators choose a "Membership Type" and only allow signups if you have that type of membership.  I'll leave this open as a reminder to implement it in this fashion.

**Comment by insrcd** [comment]
This has now been removed, and event creators can specify that a membership # is required.
