### ISSUE TITLE
Login form is quite wide

### ISSUE THREAD

**Issue by dcollinsn** [insrcd/PreRegMePublic#19]
The registration form is big, the login form is HUGE.

![image](https://cloud.githubusercontent.com/assets/9273956/12488028/a980f286-c037-11e5-907d-157f97447856.png)

In fact, when using the form, the links on the right don't even register, because there's so much horizontal separation. Here's what it looks like with a `width:30%; margin:auto`

![image](https://cloud.githubusercontent.com/assets/9273956/12488168/4a019c06-c038-11e5-8175-e37590ffe089.png)

Ahh, much better. I'm sure there's a mobile-friendly way to do this.

**Comment by insrcd** [comment]
I've created a responsive version that should be an improvement.
