### ISSUE TITLE
Failed CC registration leaves you with a useless form

### ISSUE THREAD

**Issue by dcollinsn** [insrcd/PreRegMePublic#23]
*Note: Unable to test/screenshot because I can't unregister yet.*

When registering on the dev instance using an invalid CC number, an error message is correctly displayed. However, when correcting the CC number and submitting the form again, the error message remains, and the registration is not accepted. Reloading the page is required.

**Comment by insrcd** [comment]
The token wasn't being added to the form when it regenerated. This will be fixed in the next push.
