### ISSUE TITLE
HTTP 500 on event/edit

### ISSUE THREAD

**Issue by dcollinsn** [insrcd/PreRegMePublic#24]
When clicking on the highlighted part of an event card on the Dashboard:

![image](https://cloud.githubusercontent.com/assets/9273956/12592121/109e62b4-c439-11e5-99c1-7102e25b2e78.png)

The url `http://prereg.cfapps.io/event/edit/8a7e80e25261776a015262719aa60009` is loaded, which results in an HTTP 500 internal server error.

**Comment by insrcd** [comment]
This should now be fixed.

**Comment by dcollinsn** [comment]
Clicking on this link still 500s out, but only when accessing an event I do not have edit permissions for:

https://preregdev.cfapps.io/event/edit/8a7e804a52b7ee640152b7f13a8f0000

**Comment by insrcd** [comment]
A better error message will be posted for events that you don't have access to, that link has also changed to show not edit.
