### ISSUE TITLE
Don't show links to users who can't use them

### ISSUE THREAD

**Issue by dcollinsn** [insrcd/PreRegMePublic#25]
On `/channel/list` is a "new channel" button, however "Sorry, you're not authorized to view this page."

Similarly, on `/event/list` is a link to each event's `/event/edit` screen.

This should not be visible (or should be visible but greyed out/unclickable) for users without the requisite permissions.

**Comment by insrcd** [comment]
I'll add the permissions to view those links.

**Comment by insrcd** [comment]
I have removed the /event/edit for link on the events. You should only see /channel/list if you can create new channels.
