### ISSUE TITLE
Channel list and count are not consistent

### ISSUE THREAD

**Issue by dcollinsn** [insrcd/PreRegMePublic#26]
When loading the URL `/channel/list`, an empty table is displayed, even though the system claims it is showing "1 to 2 of 2 entries".

![image](https://cloud.githubusercontent.com/assets/9273956/12592224/8c93cbc0-c439-11e5-8f4b-8b6598087ca6.png)

**Comment by insrcd** [comment]
it's counting all channels, not just ones you have access to, Ill look into fixing.

**Comment by insrcd** [comment]
This is now fixed.
