### ISSUE TITLE
"Active events" is not consistent

### ISSUE THREAD

**Issue by dcollinsn** [insrcd/PreRegMePublic#27]
The menu shows that there are 2 active events:

![image](https://cloud.githubusercontent.com/assets/9273956/12592643/52f9edd4-c43b-11e5-9cb4-c96bf3062420.png)

`event/listByStatus/Active` shows that there are 0:

![image](https://cloud.githubusercontent.com/assets/9273956/12592656/63618cfe-c43b-11e5-96a0-657e7cf470c7.png)

**Comment by insrcd** [comment]
This will be resolved in the next push.
