### ISSUE TITLE
"Keep me signed in" checkbox unusable

### ISSUE THREAD

**Issue by dcollinsn** [insrcd/PreRegMePublic#3]
The "Keep me signed in" checkbox cannot be checked/unchecked in Google Chrome Version 47.0.2526.106 m in Windows 10. Clicking on the checkbox has no effect, clicking on the text label has no effect.

The "real" HTML checkbox is hidden by CSS. Making the real HTML checkbox visible and clicking on it does work:
![image](https://cloud.githubusercontent.com/assets/9273956/12433836/4ce8092c-bed1-11e5-8bd8-e7bc01184c78.png)

**Comment by insrcd** [comment]
Removed for the time being - I default to keeping the user signed in (it's a low risk site, so I don't mind it).
