### ISSUE TITLE
403 when publishing event

### ISSUE THREAD

**Issue by dcollinsn** [insrcd/PreRegMePublic#31]
I created an event, and can see it at https://preregdev.cfapps.io/event/listByStatus/Unpublished

However, when I try to publish it, I get a rather inelegant 403 page https://preregdev.cfapps.io/event/publish/8a7e80b652c3387f0152c34ee5710001

![image](https://cloud.githubusercontent.com/assets/9273956/12903422/861c4d24-ce95-11e5-97c9-f79c54ac02e7.png)

**Comment by insrcd** [comment]
Will be fixed in next push.

**Comment by dcollinsn** [comment]
Fixed
