### ISSUE TITLE
Registration types are not saved when creating event

### ISSUE THREAD

**Issue by dcollinsn** [insrcd/PreRegMePublic#32]
When creating a new event, I can (and am required to) add a registration type:

![image](https://cloud.githubusercontent.com/assets/9273956/12903549/79eba4f4-ce96-11e5-8b1f-b250606d2a5a.png)

However, the created event does not have any registration type associated with it:

![image](https://cloud.githubusercontent.com/assets/9273956/12903556/8ba3a3f4-ce96-11e5-8922-1e02ea750e48.png)

**Comment by insrcd** [comment]
fixed in next push.
