### ISSUE TITLE
HTTP 404 on notification/read

### ISSUE THREAD

**Issue by dcollinsn** [insrcd/PreRegMePublic#34]
https://preregdev.cfapps.io/notification/read/8a7e80b652c3387f0152c35b4ddd0003

![image](https://cloud.githubusercontent.com/assets/9273956/12903660/692afc40-ce97-11e5-9308-36d57149383f.png)

**Comment by insrcd** [comment]
This is known, will leave it here so it's not duped.

2016-02-08 19:09 GMT-05:00 dcollinsn <notifications@github.com>:

**Comment by insrcd** [comment]
Notifications are now timeline entries, and it no longer 404s.
