### ISSUE TITLE
Event Reporter: Player points are not deleted when round is deleted

### ISSUE THREAD

**Issue by dcollinsn** [insrcd/PreRegMePublic#35]
If a round is deleted after results have been entered, player points are not deleted:

![image](https://cloud.githubusercontent.com/assets/9273956/12905333/5bef4c18-cea4-11e5-9f5c-bae214395da1.png)

**Comment by insrcd** [comment]
Result object isn't deleted when the round is deleted, must cascade this delete.

**Comment by insrcd** [comment]
This is now fixed.
