### ISSUE TITLE
Deleting the only round leaves you with no options

### ISSUE THREAD

**Issue by dcollinsn** [insrcd/PreRegMePublic#36]
1. Create an event
2. Pair round 1
3. Delete round 1
4. Despair, as there is no intuitive way to move forward:

![image](https://cloud.githubusercontent.com/assets/9273956/12905352/85dd69b0-cea4-11e5-881a-de3b60a41975.png)

Consider leaving the "actions" dropdown available. The only option is to go back to the Player List and click "Go To Current Round", which seems a bit unintuitive

**Comment by insrcd** [comment]
Start tournament button should be displayed, will add it.

**Comment by insrcd** [comment]
it will now give you options when you delete the last round.
