### ISSUE TITLE
Cannot drop players from player list

### ISSUE THREAD

**Issue by dcollinsn** [insrcd/PreRegMePublic#37]
It is not possible to drop players from the player list. There are checkboxes, but no buttons that I am able to see or interact with.

(The fact that there are two of you does not appear to be a bug, I think you just have two accounts)

![image](https://cloud.githubusercontent.com/assets/9273956/12905422/fe56974a-cea4-11e5-8762-b061040729cb.png)

**Comment by insrcd** [comment]
You can now drop and delete players from the player list.
