### ISSUE TITLE
Delete Round sometimes doesn't work without a reload

### ISSUE THREAD

**Issue by dcollinsn** [insrcd/PreRegMePublic#39]
1. Load https://preregdev.cfapps.io/tournament/pairings/74
2. Actions -> New Round
3. Actions -> Delete Round

has no visible effect

Reloading the page allows Actions -> Delete Round to work

I believe this is a JS error in the following code (preregme.reporter.js:280):

    this.run = function(){
        $("[data-idem-view=main]").load("/tournament/newRound/" + self.reporterInstance.tournamentId, function(json){

            reporterInstance.round = json.result.number

            self.reporterInstance.bind($("[data-idem-view=main]"))
        })
    }

Which gives the following error:

`Uncaught TypeError: Cannot read property 'number' of undefined`

**Comment by insrcd** [comment]
This is now fixed.
