### ISSUE TITLE
Add officials actually adds a player with no name

### ISSUE THREAD

**Issue by dcollinsn** [insrcd/PreRegMePublic#40]
1. Load Tournament Reporter player list
2. Enter any user's name
3. Select "Head Judge"
4. Click "+"

User is added to the "players" table as "undefined, undefined".

![image](https://cloud.githubusercontent.com/assets/9273956/12905724/7f063506-cea7-11e5-8174-f028699d0180.png)

**Comment by dcollinsn** [comment]
This data is successfully added to the database, and is visible on the correct screen/with the correct role once the player list is reloaded. This is only a bug with the JS view, it seems.

**Comment by insrcd** [comment]
Confirmed, issue with adding to the wrong table and the wrong template.

**Comment by insrcd** [comment]
This will be fixed in the next push.
