### ISSUE TITLE
Dropping duplicate player leads to unrecoverable state

### ISSUE THREAD

**Issue by dcollinsn** [insrcd/PreRegMePublic#41]
Something quite strange has happened with https://preregdev.cfapps.io/tournament/pairings/74#

There are two of you, as evidenced as my ability to add you to the player list twice

![image](https://cloud.githubusercontent.com/assets/9273956/12905815/5c344512-cea8-11e5-8bb4-3f974b2e3e4c.png)

While experimenting earlier, I dropped you from your instance of this screen:

![image](https://cloud.githubusercontent.com/assets/9273956/12905822/7948df78-cea8-11e5-9469-bafa24888da6.png)

However, I cannot access that screen from anywhere else to un-drop you - I've deleted the only round where you were paired, and that link is not available on the player list. One Lokii is still in the event:

![image](https://cloud.githubusercontent.com/assets/9273956/12905832/96eab57e-cea8-11e5-8fd6-8b985e837b96.png)

But cannot possibly be paired or get the bye:

![image](https://cloud.githubusercontent.com/assets/9273956/12905836/a6099d68-cea8-11e5-90e4-9cd438ceb7c2.png)

I suspect that some part of this system is using user ID as an index and another part is using membership number as an index, which is why dropping you has only removed one Adam Shaw from the player list, but has prevented both Adam Shaws from being paired.

**Comment by insrcd** [comment]
Duplicate players are now impossible - this was actually an issue of there being multiple linkage objects (TournamentPlayer) linked to one Player object.  It is now no longer possible for this condition to occur.
