### ISSUE TITLE
Popup error on channel edit

### ISSUE THREAD

**Issue by dcollinsn** [insrcd/PreRegMePublic#43]
1. Be me
2. Load https://preregdev.cfapps.io/channel/edit/8a7e80b652c3387f0152c34ad4660000
3. The following alert appears:

![image](https://cloud.githubusercontent.com/assets/9273956/12906116/2426041e-ceab-11e5-8050-9052fce2119e.png)

**Comment by insrcd** [comment]
yea, email addresses are only visible to Admins, I'll have to remove this
column from this table.
