### ISSUE TITLE
Remove registration -> angry JS alert

### ISSUE THREAD

**Issue by dcollinsn** [insrcd/PreRegMePublic#45]
1. Load any event edit screen (https://preregdev.cfapps.io/event/edit/8a7e803a52c37af40152c3d5f5280004)
2. Click "Registrations"
3. Click "Refund" for any user
4. Following alert appears, but the user *is* successfully removed!

![image](https://cloud.githubusercontent.com/assets/9273956/12906223/280c5a00-ceac-11e5-8714-524d95421740.png)

**Comment by insrcd** [comment]
This should be fixed
