### ISSUE TITLE
Spelling: "Wizrads" of the coast

### ISSUE THREAD

**Issue by dcollinsn** [insrcd/PreRegMePublic#49]
In the trademark disclaimer: s/registred/registered/ and s/Wizrads/Wizards/.

> KONAMI is a registered trademark of KONAMI Limited. DCI and Magic: The Gathering are a registred trademark for Wizrads of the Coast, Inc. All product and company names are trademarks™ or registered® trademarks of their respective holders. Use of them does not imply any affiliation with or endorsement by them.

**Comment by insrcd** [comment]
fix0red
