### ISSUE TITLE
Malformed JS in signup pages

### ISSUE THREAD

**Issue by dcollinsn** [insrcd/PreRegMePublic#5]
Loading https://prereg.me/event/signup/8a7e803a51c59cec01520f10dfbc0002, line 809 contains the following script tag:

`<script type="text/javascript">$(function(){ $("select").select2({theme:"bootstrap"});</script>`

The opening ( and { are unclosed. This throws:

`Uncaught SyntaxError: Unexpected end of input`

**Comment by insrcd** [comment]
This is fixed.
