### ISSUE TITLE
Feature request: Remove members from channels

### ISSUE THREAD

**Issue by dcollinsn** [insrcd/PreRegMePublic#51]
It is possible to add members to channels, but not to remove them. Perhaps I am missing a button?

![image](https://cloud.githubusercontent.com/assets/9273956/12920836/4e165f40-cf18-11e5-8134-13c8ebb20208.png)

**Comment by insrcd** [comment]
Nope, didn't add the button, will do.

**Comment by insrcd** [comment]
This will be added in the next build.
