### ISSUE TITLE
Multiple membership numbers - unable to select which one to use when registering

### ISSUE THREAD

**Issue by dcollinsn** [insrcd/PreRegMePublic#52]
When I register for an event, there is no option to choose which membership number I want to use. Further, if I register with a membership number and then add another registration number for the same game system, the event uses whichever registration number is smaller.

![image](https://cloud.githubusercontent.com/assets/9273956/12920943/e499fc9c-cf18-11e5-9536-0be0a57fd9e4.png)

![image](https://cloud.githubusercontent.com/assets/9273956/12920946/e9efb308-cf18-11e5-99a2-0981fd38ddc6.png)

**Comment by dcollinsn** [comment]
I suspect that when I register for an event, the membership number I choose should be saved with that event as well as with my profile. This way if I delete or add membership numbers to my profile, the event is not affected.

**Comment by insrcd** [comment]
I believe I need to limit 1 membership per brand, this will fix this issue.
