### ISSUE TITLE
Dashboard graphs suspiciously similar

### ISSUE THREAD

**Issue by dcollinsn** [insrcd/PreRegMePublic#53]
The graphs on the Dashboard for the following events are suspiciously exactly the same. Perhaps whatever generates these graphs is overwriting the same file?

![image](https://cloud.githubusercontent.com/assets/9273956/12921802/d58e4696-cf1c-11e5-90ff-cfdc10858462.png)

**Comment by insrcd** [comment]
Odd, must be a problem with the charting library.  Looking into it.

**Comment by insrcd** [comment]
nope, bad query, fixing.

**Comment by dcollinsn** [comment]
Fixed in dev, closing
