### ISSUE TITLE
Registrations do not add players to YuGiOh events

### ISSUE THREAD

**Issue by dcollinsn** [insrcd/PreRegMePublic#57]
1. Create an event
2. Set event type to YuGiOh
3. Optionally, set "Requires registration number"
4. Register for the event using an account with a Magic number but no YuGiOh number
5. You should be, but are not, prompted to enter a registration number
6. Registration is successful
7. Player does not appear on the ScoreKpr player list
8. Registration number on user's profile is now a YuGiOh registration number

![image](https://cloud.githubusercontent.com/assets/9273956/12924248/28f658c8-cf27-11e5-83ef-2d32f20bca9f.png)

**Comment by insrcd** [comment]
This should now be fixed.
