### ISSUE TITLE
Event -> membership number mapping does not respect brand

### ISSUE THREAD

**Issue by dcollinsn** [insrcd/PreRegMePublic#58]
If a user has both a Magic and YuGiOh registration number and registers for an event with an assigned brand, the brand is not taken into account when choosing which registration number to use:

![image](https://cloud.githubusercontent.com/assets/9273956/12924524/991b8802-cf28-11e5-9481-d712a627fc32.png)

A YuGiOh event:

![image](https://cloud.githubusercontent.com/assets/9273956/12924533/a2f20900-cf28-11e5-99c9-fe716ec2c5fd.png)

**Comment by insrcd** [comment]
Brand is a newish concept, will make sure to respect the brand of the event.

**Comment by insrcd** [comment]
This will be resolved in the next build.
