### ISSUE TITLE
Results entry shortcuts should wrap consistently

### ISSUE THREAD

**Issue by dcollinsn** [insrcd/PreRegMePublic#59]
At home, the results entry shortcuts wrap like this:

![image](https://cloud.githubusercontent.com/assets/9273956/12929406/6f8b9992-cf40-11e5-89a0-185eb66f8dbf.png)

On this widescreen monitor, they wrap like this:

![image](https://cloud.githubusercontent.com/assets/9273956/12929387/5ca62bb2-cf40-11e5-9f56-1c54d0b6e901.png)

I think they should be consistent, ideally with the first photo, wrapping after the fourth like the DCIR interface

**Comment by insrcd** [comment]
Agreed, will add a <div class="row">

**Comment by insrcd** [comment]
Row added
