### ISSUE TITLE
Unable to register for events

### ISSUE THREAD

**Issue by dcollinsn** [insrcd/PreRegMePublic#6]
When attempting to register for an event at https://prereg.me/event/signup/8a7e803a51c59cec01520f10dfbc0002

Using the test CC number 4242424242424242

An error is displayed:

`There was a problem with the information you provided. Please check your email and membership number again.`

Additionally, this error message is unclear: The form on this page doesn't ask for an email or membership number. If this is supposed to be a payment error, it should refer to the CC information that this page requests.

**Comment by insrcd** [comment]
Cool thanks for the report - I just changed the signup workflow a ton so I expect some weird errors (you used to not have to have an account to register but now you do). I'll sort through these issues tonight and hopefully you'll test this shortly.

**Comment by dcollinsn** [comment]
This now throws:

`There was an error in creating your registration No property found for name [context] for class [class me.prereg.payments.PaymentProcessor]`

**Comment by insrcd** [comment]
Yea it's not creating the proper token right now, have a fix that I'm
testing locally and will deploy once I get it all set.

**Comment by insrcd** [comment]
This should now be resolved.
