### ISSUE TITLE
Start Tournament -> Select Match = no results entry screen

### ISSUE THREAD

**Issue by dcollinsn** [insrcd/PreRegMePublic#63]
1. Create an event, add players
2. Load player list
3. Click "start tournament"
4. Select any match radio box

Expected: Results entry frame should appear

Actual:

![image](https://cloud.githubusercontent.com/assets/9273956/12930394/0a0ef8e2-cf46-11e5-80c7-ca3df9074f69.png)

**Comment by dcollinsn** [comment]
Also occurs with New Round. Following JS error may be related:

![image](https://cloud.githubusercontent.com/assets/9273956/12930615/53d3fda0-cf47-11e5-9874-9969d08e2bab.png)

![image](https://cloud.githubusercontent.com/assets/9273956/12930622/5c696d92-cf47-11e5-842e-5c7e405a3ac3.png)

**Comment by insrcd** [comment]
Fixed
