### ISSUE TITLE
When first loading ScoreKpr, select table box is missing

### ISSUE THREAD

**Issue by dcollinsn** [insrcd/PreRegMePublic#64]
1. load https://preregdev.cfapps.io/tournament/pairings/429#

Expected: Open Table box will appear for keyboard-only entry

Actual:
![image](https://cloud.githubusercontent.com/assets/9273956/12930468/790435dc-cf46-11e5-8c67-dcb762cdf543.png)

**Comment by insrcd** [comment]
Table 1 will now open automatically.
