### ISSUE TITLE
Tiebreaker coercion to 0.33 only replaces 0 tiebreaker

### ISSUE THREAD

**Issue by dcollinsn** [insrcd/PreRegMePublic#65]
1. Construct an event where some players have tiebreakers in the interval (0, 0.33)
2. View standings

Expected: MTR states tiebreakers will be coerced to a minimum of 0.33

Actual: Tiebreakers are only coerced if they are exactly 0:

![image](https://cloud.githubusercontent.com/assets/9273956/12930528/cada662e-cf46-11e5-8c83-fe08c51056f3.png)

**Comment by insrcd** [comment]
Fixed now.
