### ISSUE TITLE
Dashboard link does not go to dashboard

### ISSUE THREAD

**Issue by dcollinsn** [insrcd/PreRegMePublic#67]
![image](https://cloud.githubusercontent.com/assets/9273956/13022063/e2febc24-d1ac-11e5-9e94-20a1ac8676ef.png)

The bottom link takes you to https://preregdev.cfapps.io/, not to the dashboard.

If you want a link to the root of the site, the highlighted logo seems like a good choice

**Comment by insrcd** [comment]
will be fixed in the next push.
