### ISSUE TITLE
"Drop" button on player list does nothing

### ISSUE THREAD

**Issue by dcollinsn** [insrcd/PreRegMePublic#68]
When I click this button:

![image](https://cloud.githubusercontent.com/assets/9273956/13037915/b3af4d5a-d358-11e5-8574-cfc1acf1d16e.png)

nothing happens. Even after a reload, the player is still in the event.

**Comment by insrcd** [comment]
Seems to work here, can you post the URL? I'll test it with your account

**Comment by dcollinsn** [comment]
https://preregdev.cfapps.io/tournament/reporter/613

**Comment by insrcd** [comment]
Actions don't get bound to the table after reload.

**Comment by insrcd** [comment]
WIll be fixed in the next build.
