### ISSUE TITLE
It's real easy to delete events from the event list

### ISSUE THREAD

**Issue by dcollinsn** [insrcd/PreRegMePublic#69]
![image](https://cloud.githubusercontent.com/assets/9273956/13037930/141669b2-d359-11e5-814e-5f3cbe7a3c37.png)

From event/edit, there is at least a JS alert before the event is deleted. From event/list, there is no confirmation at all.

**Comment by insrcd** [comment]
It's a soft delete, but I'll add a confirm.

**Comment by insrcd** [comment]
Added a confirm.
