### ISSUE TITLE
Registering user doesn't add them to player list if player list has already been opened

### ISSUE THREAD

**Issue by dcollinsn** [insrcd/PreRegMePublic#71]
Steps to reproduce:

1. Create an event
2. Register at least one user
3. Open "ScoreKpr", view player list. Player list will be correct.
4. Register more users to the event.
5. Refresh player list. Any users registered since ScoreKpr was opened will not be on the player list.

![image](https://cloud.githubusercontent.com/assets/9273956/13038018/c173027c-d35a-11e5-8085-4b18c9a342e1.png)

![image](https://cloud.githubusercontent.com/assets/9273956/13038023/ce70aca4-d35a-11e5-81e9-2cbe8907cf99.png)

![image](https://cloud.githubusercontent.com/assets/9273956/13038028/d70fcac0-d35a-11e5-9025-ad3f7f7082e7.png)

**Comment by insrcd** [comment]
That's correct, adding registrations doesn't modify the tournament software - they should be added directly using the tournament software.

**Comment by dcollinsn** [comment]
This seems risky. In a real-life event, this means that opening the
Reporter before registration closes will "really screw up" your event.
Also, don't we want a way to process late entries as a "registration" event
(and bill their CC) while simultaneously adding them to the event?

**Comment by insrcd** [comment]
This is not the current use case.
