### ISSUE TITLE
Deleting the only round and returning to the player list leaves you with no options

### ISSUE THREAD

**Issue by dcollinsn** [insrcd/PreRegMePublic#72]
1. Create an event. Pair round 1.
2. Delete round 1.
3. New text appears, allowing you to "start tournament" or "return to player list"
4. Select "return to player list"
5. You now can not start the tournament.

![image](https://cloud.githubusercontent.com/assets/9273956/13038068/77357be4-d35b-11e5-9aed-f93b3c003148.png)

**Comment by insrcd** [comment]
It'll now display "start tournament" button if there are no pairings.
