### ISSUE TITLE
"New Round" appears to fail but actually succeeds

### ISSUE THREAD

**Issue by dcollinsn** [insrcd/PreRegMePublic#74]
1. Create test tournament
2. Enter all results
3. Click "New Round"
4. "Couldn't convert result to JSON" error appears, but otherwise the page thinks we are in the next round
5. Refreshing the page causes the new round to appear

![image](https://cloud.githubusercontent.com/assets/9273956/13038097/f531a996-d35b-11e5-905a-07c058c43dfb.png)

**Comment by insrcd** [comment]
Fixed a bug in the Player object, fixed this.
