### ISSUE TITLE
Standings aren't sorted right

### ISSUE THREAD

**Issue by dcollinsn** [insrcd/PreRegMePublic#78]
![image](https://cloud.githubusercontent.com/assets/9273956/13038313/6e5f91d6-d35f-11e5-9e2d-849357944338.png)

Either the second sortkey is OMW but it's ascending instead of descending, or something.

**Comment by dcollinsn** [comment]
This incorrect standing order seems to impact the top 8 cut - my Top 8 includes user12, user5, and user6, which is wrong. I can't even tell if the top 8 pairings are correct or not, but I don't believe they are.

![image](https://cloud.githubusercontent.com/assets/9273956/13038353/e0d9dd7a-d35f-11e5-8423-252f6d99b9c0.png)

**Comment by insrcd** [comment]
Fixed in the next push
