### ISSUE TITLE
Clicking on player name in results entry screen does nothing

### ISSUE THREAD

**Issue by dcollinsn** [insrcd/PreRegMePublic#79]
Clicking the highlighted link does nothing. It used to open a screen where I could edit the user name and drop/undrop/disqualify them. 

![image](https://cloud.githubusercontent.com/assets/9273956/13038388/3859c718-d360-11e5-8cfe-f0d80fb215b5.png)

**Comment by insrcd** [comment]
These are "phantom" players and don't have users - that screen expected a user. I'll modify it so it doesn't.

**Comment by insrcd** [comment]
This has been fixed.
