### ISSUE TITLE
Can't move past top 8

### ISSUE THREAD

**Issue by dcollinsn** [insrcd/PreRegMePublic#80]
1. Cut to top 8
2. Enter results
3. Refresh page
4. https://preregdev.cfapps.io/tournament/playoffPairings/965
5. "An Error Has Occurred"

**Comment by insrcd** [comment]
yea you shouldn't call playoffPairings twice, I need to have it forward to pairings and remove the ability to call playoffPairings.

**Comment by insrcd** [comment]
You can no longer call playoffPairings twice
