### ISSUE TITLE
Profile - "City" is mandatory?

### ISSUE THREAD

**Issue by dcollinsn** [insrcd/PreRegMePublic#9]
On the profile page, "City" is marked as a mandatory field. However, this is not enforced. As you can see, I am without a city. It is even possible to enter a city, save, and then remove it.

However, should City really be mandatory? If so, should it be required when you register a new account?

![image](https://cloud.githubusercontent.com/assets/9273956/12436221/447a6d7e-bee1-11e5-8004-bd1b8df40d5f.png)

**Comment by insrcd** [comment]
it should not be mandatory, I will remove that and check form validation on the profile page.

**Comment by dcollinsn** [comment]
The same is true for "First Name"

**Comment by dcollinsn** [comment]
Fixed in dev, closing
